### PR TITLE
Enable `download-cache` support in `edpm_ovn` role

### PR DESCRIPTION
**Pull request by rebtoor**

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
Kinda weird, the job failed on baremetal trying to download ovn-controller image:
```
2023-09-22T08:52:53.571436798+00:00 stdout F TASK [osp.edpm.edpm_ovn : Download needed container images] ********************
2023-09-22T08:52:53.573783815+00:00 stdout F Friday 22 September 2023  08:52:53 +0000 (0:00:00.238)       0:00:29.692 ****** 
2023-09-22T08:52:54.291113020+00:00 stdout F [0;32mok: [edpm-compute-0] => (item=quay.io/podified-antelope-centos9/openstack-ovn-controller:current-podified) => {"actions": [], "ansible_loop_var": "item", "attempts": 1, "changed": false, "image": {}, "item": "quay.io/podified-antelope-centos9/openstack-ovn-controller:current-podified", "podman_actions": ["/bin/podman image ls quay.io/podified-antelope-centos9/openstack-ovn-controller:current-podified --format json"]}[0m
2023-09-22T08:52:58.039414648+00:00 stdout F [1;30mFAILED - RETRYING: [edpm-compute-0]: Download needed container images (5 retries left).[0m
2023-09-22T08:53:07.244782107+00:00 stdout F [1;30mFAILED - RETRYING: [edpm-compute-0]: Download needed container images (4 retries left).[0m
2023-09-22T08:53:15.556673503+00:00 stdout F [1;30mFAILED - RETRYING: [edpm-compute-0]: Download needed container images (3 retries left).[0m
2023-09-22T08:53:24.207571426+00:00 stdout F [1;30mFAILED - RETRYING: [edpm-compute-0]: Download needed container images (2 retries left).[0m
2023-09-22T08:53:33.492761817+00:00 stdout F [1;30mFAILED - RETRYING: [edpm-compute-0]: Download needed container images (1 retries left).[0m
2023-09-22T08:53:41.885720941+00:00 stdout F [0;31mfailed: [edpm-compute-0] (item=quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": "quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified", "msg": "Failed to pull image quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified"}[0m
```

The same task in the podified job downloads the container image by its hash:
```
2023-09-22T08:08:14.279098635+00:00 stdout F TASK [osp.edpm.edpm_ovn : Download needed container images] ********************
2023-09-22T08:08:14.280265633+00:00 stdout F Friday 22 September 2023  08:08:14 +0000 (0:00:00.165)       0:01:10.066 ****** 
2023-09-22T08:08:17.558874381+00:00 stdout P [0;33mchanged: [edpm-compute-0] => (item=quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2) => {"actions": ["Pulled image quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2"], "ansible_loop_var": "item", "attempts": 1, "changed": true, "image": [{"Annotations": {}, "Architecture": "amd64", "Author": "", "Comment": "", "Config": {"Cmd": ["kolla_start"], "Entrypoint": ["dumb-init", "--single-child", "--"], "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "LANG=en_US.UTF-8", "container=oci"], "Labels": {"io.buildah.version": "1.31.3", "maintainer": "OpenStack Kubernetes Operator team", "org.label-schema.build-date": "20230913", "org.label-schema.license": "GPLv2", "org.label-schema.name": "CentOS Stream 9 Base Image", "org.label-schema.schema-version": "1.0", "org.label-schema.vendor": "CentOS", "tcib_build_tag": "f3d66c3ef8bcd3846aee5179926e9ae2", "tcib_managed": "true"}, "StopSignal": "SIGTERM", "User": "root"}, "Created": "2023-09-17T06:25:29.640525678Z", "Digest": "sha256:cb0466d67590977d17c5ec7094fe0b6726b39990b42fb6381bac283b7a9bcb9c", "GraphDriver": {"Data": {"LowerDir": "/var/lib/containers/storage/overlay/a1121eec51e4ad5de89a83e00d2720ccb41faf3b834702db0151060902e6be2a/diff:/var/lib/containers/storage/overlay/4e9440d876b224a0cffb4d4dd950ff121708d1dfa296a0bef29f9ff9fd2a76a1/diff:/var/lib/containers/storage/overlay/de5de285936d5b094120e8fe14092724f666d13ee6974650d5615548766a6068/diff", "UpperDir": "/var/lib/containers/storage/overlay/6e650d7571c1db4aaf94a927b3382397e32da5fc305dada05fc2dfea7e5311fa/diff", "WorkDir": "/var/lib/containers/storage/overlay/6e650d7571c1db4aaf94a927b3382397e32da5fc305dada05fc2dfea7e5311fa/work"}, "Name": "overlay"}, "History": [{"created": "2023-09-13T04:34:48.709768331Z", "created_by": "/bin/sh -c #(nop) ADD file:82a747ea35c953913bd145185ec0c00ff655a7c1cecdbe3caef0ccf100c08fa7 in / ", "empty_layer": true}, {"created": "2023-09-13T04:34:48.710802231Z", "created_by": "/bin/sh -c #(nop) LABEL org.label-schema.schema-version=\"1.0\"     org.label-schema.name=\"CentOS Stream 9 Base Image\"     org.label-schema.vendor=\"CentOS\"     org.label-schema.license=\"GPLv2\"     org.label-schema.build-date=\"20230913\"", "empty_layer": true}, {"created": "2023-09-13T04:34:52.493026796Z", "created_by": "/bin/sh -c #(nop) CMD [\"/bin/bash\"]"}, {"created": "2023-09-17T06:08:07.850630357Z", "created_by": "/bin/sh -c #(nop) LABEL maintainer=\"OpenStack Kubernetes Operator team\"", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850643167Z", "created_by": "/bin/sh -c #(nop) LABEL tcib_managed=true", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850654028Z", "created_by": "/bin/sh -c #(nop) ENV LANG=\"en_US.UTF-8\"", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850670278Z", "created_by": "/bin/sh -c #(nop) ENV container=\"oci\"", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850678798Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:08:08.125042625Z", "created_by": "/bin/sh -c if [ -f \"/etc/yum.repos.d/ubi.repo\" ]; then rm -f /etc/yum.repos.d/ubi.repo && dnf clean all && rm -rf /var/cache/dnf; fi", "empty_layer": true}, {"created": "2023-09-17T06:08:28.818372483Z", "created_by": "/bin/sh -c dnf install -y crudini && crudini --del /etc/dnf/dnf.conf main override_install_langs && crudini --set /etc/dnf/dnf.conf main clean_requirements_on_remove True && crudini --set /etc/dnf/dnf.conf main exactarch 1 && crudini --set /etc/dnf/dnf.conf main gpgcheck 1 && crudini --set /etc/dnf/dnf.conf main install_weak_deps False && if [ 'centos' == 'centos' ];then crudini --set /etc/dnf/dnf.conf main best False; fi && crudini --set /etc/dnf/dnf.conf main installonly_limit 0 && crudini --set /etc/dnf/dnf.conf main keepcache 0 && crudini --set /etc/dnf/dnf.conf main obsoletes 1 && crudini --set /etc/dnf/dnf.conf main plugins 1 && crudini --set /etc/dnf/dnf.conf main skip_missing_names_on_install False && crudini --set /etc/dnf/dnf.conf main tsflags nodocs", "empty_layer": true}, {"created": "2023-09-17T06:08:31.117740978Z", "created_by": "/bin/sh -c dnf install -y ca-certificates dumb-init glibc-langpack-en procps-ng python3 sudo util-linux-user which python-tcib-containers", "empty_layer": true}, {"created": "2023-09-17T06:08:31.373096281Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/uid_gid_manage.sh /usr/local/bin/uid_gid_manage", "empty_layer": true}, {"created": "2023-09-17T06:08:31.608762954Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/uid_gid_manage", "empty_layer": true}, {"created": "2023-09-17T06:08:32.0716298Z", "created_by": "/bin/sh -c bash /usr/local/bin/uid_gid_manage kolla hugetlbfs libvirt qemu", "empty_layer": true}, {"created": "2023-09-17T06:08:32.320127806Z", "created_by": "/bin/sh -c touch /usr/local/bin/kolla_extend_start && chmod 755 /usr/local/bin/kolla_extend_start", "empty_layer": true}, {"created": "2023-09-17T06:08:32.558443888Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/set_configs.py /usr/local/bin/kolla_set_configs", "empty_layer": true}, {"created": "2023-09-17T06:08:32.792571701Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/kolla_set_configs", "empty_layer": true}, {"created": "2023-09-17T06:08:33.027592648Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/start.sh /usr/local/bin/kolla_start", "empty_layer": true}, {"created": "2023-09-17T06:08:33.269828651Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/kolla_start", "empty_layer": true}, {"created": "2023-09-17T06:08:33.504094447Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/httpd_setup.sh /usr/local/bin/kolla_httpd_setup", "empty_layer": true}, {"created": "2023-09-17T06:08:33.740058478Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/kolla_httpd_setup", "empty_layer": true}, {"created": "2023-09-17T06:08:33.97490156Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/sudoers /etc/sudoers", "empty_layer": true}, {"created": "2023-09-17T06:08:34.210322266Z", "created_by": "/bin/sh -c chmod 440 /etc/sudoers", "empty_layer": true}, {"created": "2023-09-17T06:08:34.479346544Z", "created_by": "/bin/sh -c sed -ri '/^(passwd:|group:)/ s/systemd//g' /etc/nsswitch.conf", "empty_layer": true}, {"created": "2023-09-17T06:08:36.979436104Z", "created_by": "/bin/sh -c dnf -y reinstall which && rpm -e --nodeps tzdata && dnf -y install tzdata", "empty_layer": true}, {"created": "2023-09-17T06:08:37.242600841Z", "created_by": "/bin/sh -c mkdir -p /openstack", "empty_layer": true}, {"created": "2023-09-17T06:08:38.171226909Z", "created_by": "/bin/sh -c if [ 'centos' == 'centos' ];then if [ -n \"$(rpm -qa redhat-release)\" ];then rpm -e --nodeps redhat-release; fi ; dnf -y install centos-stream-release; fi", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395663549Z", "created_by": "/bin/sh -c dnf update --excludepkgs redhat-release -y && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395764732Z", "created_by": "/bin/sh -c #(nop) STOPSIGNAL SIGTERM", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395780382Z", "created_by": "/bin/sh -c #(nop) ENTRYPOINT [\"dumb-init\", \"--single-child\", \"--\"]", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395791763Z", "created_by": "/bin/sh -c #(nop) CMD [\"kolla_start\"]", "empty_layer": true}, {"comment": "FROM quay.io/centos/centos:stream9", "created": "2023-09-17T06:08:40.101289093Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}, {"created": "2023-09-17T06:09:33.022443537Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:10:13.386393643Z", "created_by": "/bin/sh -c dnf -y install openvswitch openvswitch-ovn-common python3-netifaces python3-openvswitch tcpdump && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"comment": "FROM quay.rdoproject.org/podified-antelope-centos9/openstack-base:f3d66
2023-09-22T08:08:17.558943383+00:00 stdout F c3ef8bcd3846aee5179926e9ae2", "created": "2023-09-17T06:10:14.858089446Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}, {"created": "2023-09-17T06:25:10.204487097Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:25:29.638637698Z", "created_by": "/bin/sh -c dnf -y install openvswitch-ovn-host && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"comment": "FROM quay.rdoproject.org/podified-antelope-centos9/openstack-ovn-base:f3d66c3ef8bcd3846aee5179926e9ae2", "created": "2023-09-17T06:25:30.31692663Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}], "Id": "107730a3cb117f443506ba5a29fb63003be09e9710ab5be462d3e9613a3e2fc9", "Labels": {"io.buildah.version": "1.31.3", "maintainer": "OpenStack Kubernetes Operator team", "org.label-schema.build-date": "20230913", "org.label-schema.license": "GPLv2", "org.label-schema.name": "CentOS Stream 9 Base Image", "org.label-schema.schema-version": "1.0", "org.label-schema.vendor": "CentOS", "tcib_build_tag": "f3d66c3ef8bcd3846aee5179926e9ae2", "tcib_managed": "true"}, "ManifestType": "application/vnd.docker.distribution.manifest.v2+json", "NamesHistory": ["quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2"], "Os": "linux", "Parent": "", "RepoDigests": ["quay.io/podified-antelope-centos9/openstack-ovn-controller@sha256:cb0466d67590977d17c5ec7094fe0b6726b39990b42fb6381bac283b7a9bcb9c"], "RepoTags": ["quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2"], "RootFS": {"Layers": ["sha256:de5de285936d5b094120e8fe14092724f666d13ee6974650d5615548766a6068", "sha256:c5efc539652bd9460d9a7e2915f02789671493e5bb8478db17154c3f8d838e8a", "sha256:b045caddf5925eab121310f9207ce17187314ef65c31da3047e790b014f437cd", "sha256:f6887f56deb55efd5cb0c97563388a9c0aded37c18bc449936187093707f0f86"], "Type": "layers"}, "Size": 329294243, "User": "root", "Version": "", "VirtualSize": 329294243}], "item": "quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2", "podman_actions": ["/bin/podman image ls quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2 --format json", "/bin/podman pull quay.io/podified-antelope-centos9/openstack-ovn-controller:f3d66c3ef8bcd3846aee5179926e9ae2 -q", "/bin/podman inspect 107730a3cb117f443506ba5a29fb63003be09e9710ab5be462d3e9613a3e2fc9 --format json"]}[0m
2023-09-22T08:08:28.121616685+00:00 stdout P [0;33mchanged: [edpm-compute-0] => (item=quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2) => {"actions": ["Pulled image quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2"], "ansible_loop_var": "item", "attempts": 1, "changed": true, "image": [{"Annotations": {}, "Architecture": "amd64", "Author": "", "Comment": "", "Config": {"Cmd": ["kolla_start"], "Entrypoint": ["dumb-init", "--single-child", "--"], "Env": ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "LANG=en_US.UTF-8", "container=oci"], "Labels": {"io.buildah.version": "1.31.3", "maintainer": "OpenStack Kubernetes Operator team", "org.label-schema.build-date": "20230913", "org.label-schema.license": "GPLv2", "org.label-schema.name": "CentOS Stream 9 Base Image", "org.label-schema.schema-version": "1.0", "org.label-schema.vendor": "CentOS", "tcib_build_tag": "f3d66c3ef8bcd3846aee5179926e9ae2", "tcib_managed": "true"}, "StopSignal": "SIGTERM", "User": "neutron"}, "Created": "2023-09-17T06:20:24.143790659Z", "Digest": "sha256:20496b53007de92bad9fe004154ce0b5a3ff7b46c07f436dc9936f1a07853d8e", "GraphDriver": {"Data": {"LowerDir": "/var/lib/containers/storage/overlay/b7c4a8c7c14c4ff79ba1510da902d98f20ed20d80971b42bee10c3f9328d55d5/diff:/var/lib/containers/storage/overlay/b6979c94022a117e173705aee4e924b3952882fe5a8943b394ef28cbfe1d5fa7/diff:/var/lib/containers/storage/overlay/abc87447bf828a72a2ecf8de1b813bc92de4c04cb5895ef2ac28d71bf76a5598/diff:/var/lib/containers/storage/overlay/4e9440d876b224a0cffb4d4dd950ff121708d1dfa296a0bef29f9ff9fd2a76a1/diff:/var/lib/containers/storage/overlay/de5de285936d5b094120e8fe14092724f666d13ee6974650d5615548766a6068/diff", "UpperDir": "/var/lib/containers/storage/overlay/045eec84c8d1ecb4f71fdb901648bbd4f74890125f2dfbec79faf1b78ae00572/diff", "WorkDir": "/var/lib/containers/storage/overlay/045eec84c8d1ecb4f71fdb901648bbd4f74890125f2dfbec79faf1b78ae00572/work"}, "Name": "overlay"}, "History": [{"created": "2023-09-13T04:34:48.709768331Z", "created_by": "/bin/sh -c #(nop) ADD file:82a747ea35c953913bd145185ec0c00ff655a7c1cecdbe3caef0ccf100c08fa7 in / ", "empty_layer": true}, {"created": "2023-09-13T04:34:48.710802231Z", "created_by": "/bin/sh -c #(nop) LABEL org.label-schema.schema-version=\"1.0\"     org.label-schema.name=\"CentOS Stream 9 Base Image\"     org.label-schema.vendor=\"CentOS\"     org.label-schema.license=\"GPLv2\"     org.label-schema.build-date=\"20230913\"", "empty_layer": true}, {"created": "2023-09-13T04:34:52.493026796Z", "created_by": "/bin/sh -c #(nop) CMD [\"/bin/bash\"]"}, {"created": "2023-09-17T06:08:07.850630357Z", "created_by": "/bin/sh -c #(nop) LABEL maintainer=\"OpenStack Kubernetes Operator team\"", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850643167Z", "created_by": "/bin/sh -c #(nop) LABEL tcib_managed=true", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850654028Z", "created_by": "/bin/sh -c #(nop) ENV LANG=\"en_US.UTF-8\"", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850670278Z", "created_by": "/bin/sh -c #(nop) ENV container=\"oci\"", "empty_layer": true}, {"created": "2023-09-17T06:08:07.850678798Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:08:08.125042625Z", "created_by": "/bin/sh -c if [ -f \"/etc/yum.repos.d/ubi.repo\" ]; then rm -f /etc/yum.repos.d/ubi.repo && dnf clean all && rm -rf /var/cache/dnf; fi", "empty_layer": true}, {"created": "2023-09-17T06:08:28.818372483Z", "created_by": "/bin/sh -c dnf install -y crudini && crudini --del /etc/dnf/dnf.conf main override_install_langs && crudini --set /etc/dnf/dnf.conf main clean_requirements_on_remove True && crudini --set /etc/dnf/dnf.conf main exactarch 1 && crudini --set /etc/dnf/dnf.conf main gpgcheck 1 && crudini --set /etc/dnf/dnf.conf main install_weak_deps False && if [ 'centos' == 'centos' ];then crudini --set /etc/dnf/dnf.conf main best False; fi && crudini --set /etc/dnf/dnf.conf main installonly_limit 0 && crudini --set /etc/dnf/dnf.conf main keepcache 0 && crudini --set /etc/dnf/dnf.conf main obsoletes 1 && crudini --set /etc/dnf/dnf.conf main plugins 1 && crudini --set /etc/dnf/dnf.conf main skip_missing_names_on_install False && crudini --set /etc/dnf/dnf.conf main tsflags nodocs", "empty_layer": true}, {"created": "2023-09-17T06:08:31.117740978Z", "created_by": "/bin/sh -c dnf install -y ca-certificates dumb-init glibc-langpack-en procps-ng python3 sudo util-linux-user which python-tcib-containers", "empty_layer": true}, {"created": "2023-09-17T06:08:31.373096281Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/uid_gid_manage.sh /usr/local/bin/uid_gid_manage", "empty_layer": true}, {"created": "2023-09-17T06:08:31.608762954Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/uid_gid_manage", "empty_layer": true}, {"created": "2023-09-17T06:08:32.0716298Z", "created_by": "/bin/sh -c bash /usr/local/bin/uid_gid_manage kolla hugetlbfs libvirt qemu", "empty_layer": true}, {"created": "2023-09-17T06:08:32.320127806Z", "created_by": "/bin/sh -c touch /usr/local/bin/kolla_extend_start && chmod 755 /usr/local/bin/kolla_extend_start", "empty_layer": true}, {"created": "2023-09-17T06:08:32.558443888Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/set_configs.py /usr/local/bin/kolla_set_configs", "empty_layer": true}, {"created": "2023-09-17T06:08:32.792571701Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/kolla_set_configs", "empty_layer": true}, {"created": "2023-09-17T06:08:33.027592648Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/start.sh /usr/local/bin/kolla_start", "empty_layer": true}, {"created": "2023-09-17T06:08:33.269828651Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/kolla_start", "empty_layer": true}, {"created": "2023-09-17T06:08:33.504094447Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/httpd_setup.sh /usr/local/bin/kolla_httpd_setup", "empty_layer": true}, {"created": "2023-09-17T06:08:33.740058478Z", "created_by": "/bin/sh -c chmod 755 /usr/local/bin/kolla_httpd_setup", "empty_layer": true}, {"created": "2023-09-17T06:08:33.97490156Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/base/sudoers /etc/sudoers", "empty_layer": true}, {"created": "2023-09-17T06:08:34.210322266Z", "created_by": "/bin/sh -c chmod 440 /etc/sudoers", "empty_layer": true}, {"created": "2023-09-17T06:08:34.479346544Z", "created_by": "/bin/sh -c sed -ri '/^(passwd:|group:)/ s/systemd//g' /etc/nsswitch.conf", "empty_layer": true}, {"created": "2023-09-17T06:08:36.979436104Z", "created_by": "/bin/sh -c dnf -y reinstall which && rpm -e --nodeps tzdata && dnf -y install tzdata", "empty_layer": true}, {"created": "2023-09-17T06:08:37.242600841Z", "created_by": "/bin/sh -c mkdir -p /openstack", "empty_layer": true}, {"created": "2023-09-17T06:08:38.171226909Z", "created_by": "/bin/sh -c if [ 'centos' == 'centos' ];then if [ -n \"$(rpm -qa redhat-release)\" ];then rpm -e --nodeps redhat-release; fi ; dnf -y install centos-stream-release; fi", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395663549Z", "created_by": "/bin/sh -c dnf update --excludepkgs redhat-release -y && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395764732Z", "created_by": "/bin/sh -c #(nop) STOPSIGNAL SIGTERM", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395780382Z", "created_by": "/bin/sh -c #(nop) ENTRYPOINT [\"dumb-init\", \"--single-child\", \"--\"]", "empty_layer": true}, {"created": "2023-09-17T06:08:39.395791763Z", "created_by": "/bin/sh -c #(nop) CMD [\"kolla_start\"]", "empty_layer": true}, {"comment": "FROM quay.io/centos/centos:stream9", "created": "2023-09-17T06:08:40.101289093Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}, {"created": "2023-09-17T06:09:24.285087716Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:09:50.728406261Z", "created_by": "/bin/sh -c dnf ins
2023-09-22T08:08:28.121671377+00:00 stdout F tall -y python3-barbicanclient python3-cinderclient python3-designateclient python3-glanceclient python3-gnocchiclient python3-ironicclient python3-keystoneclient python3-manilaclient python3-neutronclient python3-novaclient python3-octaviaclient python3-openstackclient python3-swiftclient python3-pymemcache && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"comment": "FROM quay.rdoproject.org/podified-antelope-centos9/openstack-base:f3d66c3ef8bcd3846aee5179926e9ae2", "created": "2023-09-17T06:09:53.459212616Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}, {"created": "2023-09-17T06:11:49.930955198Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:11:50.418840813Z", "created_by": "/bin/sh -c bash /usr/local/bin/uid_gid_manage neutron", "empty_layer": true}, {"created": "2023-09-17T06:12:49.257046177Z", "created_by": "/bin/sh -c dnf -y install iputils net-tools openstack-neutron openstack-neutron-rpc-server openstack-neutron-ml2 openvswitch python3-networking-baremetal python3-openvswitch && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"created": "2023-09-17T06:12:55.597350924Z", "created_by": "/bin/sh -c cp /usr/share/tcib/container-images/kolla/neutron-base/neutron_sudoers /etc/sudoers.d/neutron_sudoers", "empty_layer": true}, {"created": "2023-09-17T06:13:04.881721596Z", "created_by": "/bin/sh -c chmod 440 /etc/sudoers.d/neutron_sudoers", "empty_layer": true}, {"comment": "FROM quay.rdoproject.org/podified-antelope-centos9/openstack-os:f3d66c3ef8bcd3846aee5179926e9ae2", "created": "2023-09-17T06:13:11.226682152Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}, {"created": "2023-09-17T06:19:25.241987937Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:19:56.466652659Z", "created_by": "/bin/sh -c dnf -y install libseccomp podman && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"comment": "FROM quay.rdoproject.org/podified-antelope-centos9/openstack-neutron-base:f3d66c3ef8bcd3846aee5179926e9ae2", "created": "2023-09-17T06:19:59.110462271Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}, {"created": "2023-09-17T06:20:04.86833782Z", "created_by": "/bin/sh -c #(nop) USER root", "empty_layer": true}, {"created": "2023-09-17T06:20:24.142119775Z", "created_by": "/bin/sh -c dnf -y install python3-networking-ovn-metadata-agent && dnf clean all && rm -rf /var/cache/dnf", "empty_layer": true}, {"created": "2023-09-17T06:20:24.142187827Z", "created_by": "/bin/sh -c #(nop) USER neutron", "empty_layer": true}, {"comment": "FROM quay.rdoproject.org/podified-antelope-centos9/openstack-neutron-agent-base:f3d66c3ef8bcd3846aee5179926e9ae2", "created": "2023-09-17T06:20:26.204805568Z", "created_by": "/bin/sh -c #(nop) LABEL \"tcib_build_tag\"=\"f3d66c3ef8bcd3846aee5179926e9ae2\""}], "Id": "f21431ca499c3a9aacca554e94986d203af5133fa6a763c2cf86ba7dde6f39fd", "Labels": {"io.buildah.version": "1.31.3", "maintainer": "OpenStack Kubernetes Operator team", "org.label-schema.build-date": "20230913", "org.label-schema.license": "GPLv2", "org.label-schema.name": "CentOS Stream 9 Base Image", "org.label-schema.schema-version": "1.0", "org.label-schema.vendor": "CentOS", "tcib_build_tag": "f3d66c3ef8bcd3846aee5179926e9ae2", "tcib_managed": "true"}, "ManifestType": "application/vnd.docker.distribution.manifest.v2+json", "NamesHistory": ["quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2"], "Os": "linux", "Parent": "", "RepoDigests": ["quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn@sha256:20496b53007de92bad9fe004154ce0b5a3ff7b46c07f436dc9936f1a07853d8e"], "RepoTags": ["quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2"], "RootFS": {"Layers": ["sha256:de5de285936d5b094120e8fe14092724f666d13ee6974650d5615548766a6068", "sha256:c5efc539652bd9460d9a7e2915f02789671493e5bb8478db17154c3f8d838e8a", "sha256:8ef2c52c6a730a509eb41ba67ab953e05e1f5609a66b128723f7e0ab63342308", "sha256:20670cc0ab1da8b53942e50b11a2e9332542a3ee8e3ebbcb2412cd4ad70f5efe", "sha256:2a1cf2e331e94ebfe1c69904c4b5b5de5480d513c326095b026767b549806061", "sha256:6aa5ea860fa848fd44a747fc8ad5560add32007315a4689567d7c1d496375c63"], "Type": "layers"}, "Size": 758132935, "User": "neutron", "Version": "", "VirtualSize": 758132935}], "item": "quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2", "podman_actions": ["/bin/podman image ls quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2 --format json", "/bin/podman pull quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:f3d66c3ef8bcd3846aee5179926e9ae2 -q", "/bin/podman inspect f21431ca499c3a9aacca554e94986d203af5133fa6a763c2cf86ba7dde6f39fd --format json"]}[0m
```

I'll try to rerun the job but i'm testing it locally

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
i pinged @raukadah to understand why download of the ovn images from quay is failing on baremetal job

**Comment by slagle** [comment]
Resources were increased for the VM used by the baremetal job, which is why it's passing. Along with https://github.com/openstack-k8s-operators/dataplane-operator/pull/429

**Review by slagle — APPROVED** [review]

**Pull request merged**
