### PR TITLE
Revert "Peform DNF update on edpm node"

### PR DESCRIPTION
**Pull request by bogdando**
Resubmitting https://github.com/openstack-k8s-operators/edpm-ansible/pull/531

This reverts commit c3ec651573761d3ae11949c418074a0bc335fd28.

A global update doesn't work because of OVS upgrades and repo-setup considerations.

This revert is needed to unblock adoption of decontainerized libvirt (alongside https://github.com/openstack-k8s-operators/data-plane-adoption/pull/241), and to enable workloads adoption testing.

Related work https://github.com/openstack-k8s-operators/edpm-ansible/pull/532 is blocked on inputs from OVN and upgrades teams, we need to fix the regression by reverting the main cause quickly

Unblocks [OSPRH-3123](https://issues.redhat.com/browse/OSPRH-3123)
Unblocks [OSPRH-813](https://issues.redhat.com/browse/OSPRH-813)
Ublocks [OSPRH-84](https://issues.redhat.com/browse/OSPRH-84)

### CODE REVIEW

**Comment by bogdando** [comment]
@marios this revert will break CI periodic pipeline. However, it is need to fix regression for adoption of libvirt and Nova, which is in the priority for Q1. The periodic pipeline would have to be fixed after this revert submitted

**Comment by bogdando** [comment]
> break greenfiled if you are using a image that has an older (openstack-selinux) version install

that's a boomer really. sigh

**Review by slagle — COMMENTED** [review]
+2

Let's move forward with this revert. We don't want every ansible execution to trigger part of a minor update.

**Comment by fao89** [comment]
Maybe this upgrade logic should be a service
https://github.com/openstack-k8s-operators/install_yamls/pull/699/files

**Pull request merged**
