### PR TITLE
Storing extra vars as a runner env file

### PR DESCRIPTION
**Pull request by jpodivin**
Depends-On: https://github.com/openstack-k8s-operators/openstack-ansibleee-operator/pull/246

### CODE REVIEW

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

content provider failed with:
```
Error: creating build container: initializing source docker://quay.io/openstack-k8s-operators/openstack-ansibleee-operator-bundle:3cea9a4c30a0cb722241d9dcd98e0967f64ed666: reading manifest 3cea9a4c30a0cb722241d9dcd98e0967f64ed666 in quay.io/openstack-k8s-operators/openstack-ansibleee-operator-bundle: received unexpected HTTP status: 502 Bad Gateway
```

**Comment by jpodivin** [comment]
recheck 
node failures

**Comment by jpodivin** [comment]
recheck

```
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v3/collections/fedora/linux_system_roles/versions/0.0.2/': The read operation timed out
```

**Review by slagle — APPROVED** [review]

**Pull request merged**
