### PR TITLE
Ceilometer will log to stdout, removing log dir creation

### PR DESCRIPTION
**Pull request by jlarriba**
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/244

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
+2

**Review by rebtoor — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

`RETRY_LIMIT`

**Comment by jlarriba** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by jlarriba** [comment]
The error is solved by https://github.com/openstack-k8s-operators/telemetry-operator/pull/249, but it is not yet being picked up.

**Comment by rebtoor** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Comment by jlarriba** [comment]
This PR is on hold because it depends on a change in the telemetry-operator. openstack-operator has not yet been upgraded to pick up the latest telemetry-operator changes because of a failure in the adoption test (see https://github.com/openstack-k8s-operators/openstack-operator/pull/599).

Once that PR is merged, we could run these tests.

**Comment by jlarriba** [comment]
recheck

The corresponding changes from telemetry-operator are now picked up by openstack-operator.

**Comment by jlarriba** [comment]
recheck

A timeopout happened while trying to run the libvirt DataPlaneService. It does not happen on other PRs, so it might be already fixed.

**Pull request merged**
