### PR TITLE
[edpm_users]Add support for adding user to groups

### PR DESCRIPTION
**Pull request by gibizer**

### CODE REVIEW

**Comment by gibizer** [comment]
recheck
```
TASK [set_openstack_containers : Get all openstack pods output_dir={{ cifmw_set_openstack_containers_basedir }}/artifacts, script=oc get pods -n {{ cifmw_install_yamls_defaults['OPERATOR_NAMESPACE'] }} -o name] ***
Friday 20 October 2023  11:19:33 -0400 (0:00:00.041)       0:15:32.884 ******** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "error: You must be logged in to the server (Unauthorized)\n", "stdout_lines": ["error: You must be logged in to the server (Unauthorized)"]}
```

**Review by slagle — APPROVED** [review]

**Comment by gibizer** [comment]
@slagle could you add our lgtm back?

**Pull request merged**
