### PR TITLE
Make `edpm_chrony` role compliant with ansible-lint `production` profile

### PR DESCRIPTION
**Pull request by rebtoor**
- removed `README.rst`
- removed `tests` since we rely on molecule for role testing

Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/415

### CODE REVIEW

**Comment by rebtoor** [comment]
recheck

`RETRY_LIMIT`, it seems that it couldn't download the libvirt collection due to a transient network error

**Review by jpodivin — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

(RETRY_LIMIT)

**Comment by rebtoor** [comment]
recheck

```
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "extra_data": {"data": null, "details": "504 Gateway Time-out: The server didn't respond in time.: ", "response": "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"}, "msg": "HttpException: 504: Server Error for url: http://neutron-public-openstack.apps-crc.testing/v2.0/networks, 504 Gateway Time-out: The server didn't respond in time.: "}
```

**Comment by rebtoor** [comment]
recheck

(it didn't even start the deploy on the compute node)

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
For the `cifmw-crc-podified-edpm-baremetal` job it seems that compute node has been deployed. There are also all services logs without significant errors. Here's a snippet of the job output [log](https://logserver.rdoproject.org/96/396/1cdbb00fd4cc49422378b91955351796cb3a1011/github-check/podified-multinode-edpm-deployment-crc/1f9719e/job-output.txt).

```
2023-10-08 11:04:09.062303 | controller | TASK [edpm_deploy_baremetal : Wait for OpenStackDataPlaneNodeSet to be Ready _raw_params=oc wait --timeout={{ cifmw_edpm_deploy_baremetal_wait_dataplane_timeout_mins }}m --for=condition=Ready openstackdataplanenodeset openstack-edpm-ipam -n {{ cifmw_install_yamls_defaults['NAMESPACE'] }}] ***
2023-10-08 11:04:09.062309 | controller | Sunday 08 October 2023  11:04:09 -0400 (0:00:00.041)       0:25:37.557 ********
2023-10-08 11:20:44.570125 | controller | changed: [localhost]
```
The failure is on "[Post-deployment admin setup steps]" playbook, in the os-net-config role.

```
2023-10-08 11:20:54.963298 | controller | TASK [os_net_setup : Process network list elements admin_state_up={{ net_args.admin_state_up | default(omit) }}, dns_domain={{ net_args.dns_domain | default(omit) }}, external={{ net_args.external | default(omit) }}, mtu={{ net_args.mtu | default(omit) }}, name={{ net_args.name | default(omit) }}, port_security_enabled={{ net_args.port_security_enabled | default(omit) }}, provider_network_type={{ net_args.provider_network_type | default(omit) }}, provider_physical_network={{ net_args.provider_physical_network | default(omit) }}, provider_segmentation_id={{ net_args.provider_segmentation_id | default(omit) }}, shared={{ net_args.shared | default(omit) }}, region_name={{ region_name }}, state=present, auth={{ openstack_auth }}, validate_certs={{ cifmw_os_net_setup_verify_tls }}] ***
2023-10-08 11:20:54.963309 | controller | Sunday 08 October 2023  11:20:54 -0400 (0:00:00.054)       0:42:23.458 ********
2023-10-08 11:27:28.671037 | controller | FAILED - RETRYING: [localhost]: Process network list elements (10 retries left).
2023-10-08 11:27:28.671121 | controller | FAILED - RETRYING: [localhost]: Process network list elements (9 retries left).
2023-10-08 11:27:28.671132 | controller | FAILED - RETRYING: [localhost]: Process network list elements (8 retries left).
2023-10-08 11:27:28.671142 | controller | FAILED - RETRYING: [localhost]: Process network list elements (7 retries left).
2023-10-08 11:27:28.671150 | controller | FAILED - RETRYING: [localhost]: Process network list elements (6 retries left).
2023-10-08 11:27:28.671159 | controller | FAILED - RETRYING: [localhost]: Process network list elements (5 retries left).
2023-10-08 11:27:28.671167 | controller | FAILED - RETRYING: [localhost]: Process network list elements (4 retries left).
2023-10-08 11:27:28.671176 | controller | FAILED - RETRYING: [localhost]: Process network list elements (3 retries left).
2023-10-08 11:27:28.671185 | controller | FAILED - RETRYING: [localhost]: Process network list elements (2 retries left).
2023-10-08 11:27:28.671193 | controller | FAILED - RETRYING: [localhost]: Process network list elements (1 retries left).
2023-10-08 11:27:28.671202 | controller | fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "extra_data": {"data": null, "details": "504 Gateway Time-out: The server didn't respond in time.: ", "response": "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"}, "msg": "HttpException: 504: Server Error for url: http://neutron-public-openstack.apps-crc.testing/v2.0/networks, 504 Gateway Time-out: The server didn't respond in time.: "}
```

In the same way, the `podified-multinode-edpm-deployment-crc` job output [log](https://logserver.rdoproject.org/96/396/1cdbb00fd4cc49422378b91955351796cb3a1011/github-check/podified-multinode-edpm-deployment-crc/1f9719e/job-output.txt) shows that DataPlaneNode resources have been deployed correctly:

```
2023-10-08 10:58:24.812467 | controller | TASK [edpm_deploy : Wait for OpenStackDataPlaneNodeSet to be deployed _raw_params=oc wait OpenStackDataPlaneNodeSet {{ cr_name }} --namespace={{ cifmw_install_yamls_defaults['NAMESPACE'] }} --for=condition=ready --timeout={{ cifmw_edpm_deploy_timeout }}m] ***
2023-10-08 10:58:24.812476 | controller | Sunday 08 October 2023  10:58:24 -0400 (0:00:00.723)       0:16:41.621 ********
2023-10-08 11:13:05.962284 | controller | changed: [localhost]
```

The failure is in the same task as the baremetal job:
```
2023-10-08 11:13:14.721299 | controller | TASK [os_net_setup : Process network list elements admin_state_up={{ net_args.admin_state_up | default(omit) }}, dns_domain={{ net_args.dns_domain | default(omit) }}, external={{ net_args.external | default(omit) }}, mtu={{ net_args.mtu | default(omit) }}, name={{ net_args.name | default(omit) }}, port_security_enabled={{ net_args.port_security_enabled | default(omit) }}, provider_network_type={{ net_args.provider_network_type | default(omit) }}, provider_physical_network={{ net_args.provider_physical_network | default(omit) }}, provider_segmentation_id={{ net_args.provider_segmentation_id | default(omit) }}, shared={{ net_args.shared | default(omit) }}, region_name={{ region_name }}, state=present, auth={{ openstack_auth }}, validate_certs={{ cifmw_os_net_setup_verify_tls }}] ***
2023-10-08 11:13:14.721325 | controller | Sunday 08 October 2023  11:13:14 -0400 (0:00:00.049)       0:31:31.529 ********
2023-10-08 11:19:46.506496 | controller | FAILED - RETRYING: [localhost]: Process network list elements (10 retries left).
2023-10-08 11:19:46.506585 | controller | FAILED - RETRYING: [localhost]: Process network list elements (9 retries left).
2023-10-08 11:19:46.506592 | controller | FAILED - RETRYING: [localhost]: Process network list elements (8 retries left).
2023-10-08 11:19:46.506597 | controller | FAILED - RETRYING: [localhost]: Process network list elements (7 retries left).
2023-10-08 11:19:46.506602 | controller | FAILED - RETRYING: [localhost]: Process network list elements (6 retries left).
2023-10-08 11:19:46.506607 | controller | FAILED - RETRYING: [localhost]: Process network list elements (5 retries left).
2023-10-08 11:19:46.506629 | controller | FAILED - RETRYING: [localhost]: Process network list elements (4 retries left).
2023-10-08 11:19:46.506634 | controller | FAILED - RETRYING: [localhost]: Process network list elements (3 retries left).
2023-10-08 11:19:46.506639 | controller | FAILED - RETRYING: [localhost]: Process network list elements (2 retries left).
2023-10-08 11:19:46.506644 | controller | FAILED - RETRYING: [localhost]: Process network list elements (1 retries left).
2023-10-08 11:19:46.506649 | controller | fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "extra_data": {"data": null, "details": "504 Gateway Time-out: The server didn't respond in time.: ", "response": "<html><body><h1>504 Gateway Time-out</h1>\nThe server didn't respond in time.\n</body></html>\n"}, "msg": "HttpException: 504: Server Error for url: http://neutron-public-openstack.apps-crc.testing/v2.0/networks, 504 Gateway Time-out: The server didn't respond in time.: "}
```

I won't trigger any `recheck` until the issue is clear and fixed.

**Comment by rebtoor** [comment]
recheck

**Pull request merged**
