### PR TITLE
Argspec fot the edpm_hosts_entries role

### PR DESCRIPTION
**Pull request by jpodivin**
Patch also sets sensible defaults for all variables.

### CODE REVIEW

**Comment by rabi** [comment]
We don't use this role[1] anymore I think. Let's drop it completely.

[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/260

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
> We don't use this role[1] anymore I think. Let's drop it completely.
> 
> [1] [openstack-k8s-operators/dataplane-operator#260](https://github.com/openstack-k8s-operators/dataplane-operator/pull/260)

Ack. Let's get rid of it.

**Comment by jpodivin** [comment]
The role has been dropped by [1], thus eliminating its only usage. I'll remove the role here as well.

[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/260

**Comment by jpodivin** [comment]
Removal PR has been opened. https://github.com/openstack-k8s-operators/edpm-ansible/pull/248

**Pull request closed without merging**
