### PR TITLE
Revert "Update telemetry role to deploy Kepler"

### PR DESCRIPTION
**Pull request by gibizer**
This reverts commit 0859e4e7455a5054c12a00c6a79386985ea90127.

Related-Issue: [OSPCIX-502](https://issues.redhat.com//browse/OSPCIX-502)
Related-Issue: [OSPCIX-503](https://issues.redhat.com//browse/OSPCIX-503)

### CODE REVIEW

**Comment by gibizer** [comment]
According our data this PR proves that the VM boot slowdown is caused by the kepler integration see the last comment in https://issues.redhat.com/browse/OSPCIX-503 with the details.

**Comment by jlarriba** [comment]
recheck

**Review by bshephar — APPROVED** [review]

**Comment by gibizer** [comment]
recheck 
tempest never started as the pod cannot fit:
```
  Warning  FailedScheduling  3s (x37 over 68m)  default-scheduler  0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```

**Comment by gibizer** [comment]
the tempest pod is still unscheduleable:
```
  Warning  FailedScheduling  1s (x33 over 68m)  default-scheduler  0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```
https://softwarefactory-project.io/zuul/t/rdoproject.org/build/b8035c77e45141de8c4630729aca062f/log/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/tempest-tests-28kfd/tempest-tests-28kfd-describe

Either the available RAM in crc is decreased or some of our the controlplane memory consumption is increased making tempest not fit any more.

**Comment by karelyatin** [comment]
The failure in edpm-ansible-tempest-multinode is real one. triggered by https://github.com/openstack-k8s-operators/test-operator/pull/222 which doubled the memory requirement to 8 GB, it's too much for CI, don't know why tempest needs that much memory and cpu

**Comment by gibizer** [comment]
> The failure in edpm-ansible-tempest-multinode is real one. triggered by [openstack-k8s-operators/test-operator#222](https://github.com/openstack-k8s-operators/test-operator/pull/222) which doubled the memory requirement to 8 GB, it's too much for CI, don't know why tempest needs that much memory and cpu

We are discussing a way forward over slack...

**Comment by karelyatin** [comment]
recheck test-operator revert landed

**Pull request merged**
