### PR TITLE
Add tc command

### PR DESCRIPTION
**Pull request by kajinamit**
The command allows us to capture qdisc drop counter, which is useful for debugging packet loss problems.

### CODE REVIEW

**Comment by kajinamit** [comment]
This was done in TripleO by https://review.opendev.org/c/openstack/tripleo-ansible/+/890867 .

**Review by jpodivin — APPROVED** [review]
/lgtm

**Review by rebtoor — APPROVED** [review]

**Review by slagle — APPROVED** [review]

**Comment by kajinamit** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by kajinamit** [comment]
/override rdoproject.org/github-check

All jobs passed one.

**Pull request merged**
