### PR TITLE
Removing edpm_chrony role and all its references

### PR DESCRIPTION
**Pull request by jpodivin**
The checks for presence of vars were removed as well.

### CODE REVIEW

**Comment by jpodivin** [comment]
/recheck 

```
2023-11-10 08:52:00.512461 | controller | TASK [edpm_deploy_baremetal : Register the list of compute nodes _raw_params=oc get bmh -n {{ cifmw_install_yamls_defaults['NAMESPACE'] }}] ***
2023-11-10 08:52:00.512467 | controller | Friday 10 November 2023  08:52:00 -0500 (0:04:13.197)       0:25:18.044 *******
2023-11-10 08:52:01.931669 | controller | fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "get", "bmh", "-n", "openstack"], "delta": "0:00:01.168778", "end": "2023-11-10 08:52:01.903093", "msg": "non-zero return code", "rc": 1, "start": "2023-11-10 08:52:00.734315", "stderr": "error: You must be logged in to the server (Unauthorized)", "stderr_lines": ["error: You must be logged in to the server (Unauthorized)"], "stdout": "", "stdout_lines": []}
```

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

```
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v3/collections/community/general/': The read operation timed out
Error: building at STEP "RUN cd /var/tmp/edpm-ansible &&     ansible-galaxy collection install -U --timeout 120 -r requirements.yml --collections-path "/usr/share/ansible/collections" &&     ansible-galaxy collection install -U $REMOTE_SOURCE_DIR --collections-path "/usr/share/ansible/collections"": while running runtime: exit status 1
gmake: *** [Makefile:44: openstack_ansibleee_build] Error 1
```

**Comment by rebtoor** [comment]
recheck

`RETRY_LIMIT`

**Comment by rebtoor** [comment]
recheck

`RETRY_LIMIT`

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
