### PR TITLE
Import the chrony role inside the project

### PR DESCRIPTION
**Pull request by rebtoor**

### CODE REVIEW

**Comment by rebtoor** [comment]
I created a runner image with embedded chrony role and it works. If you want to try it: quay.io/ralfieri/openstack-ansibleee-runner:chrony

**Comment by raukadah** [comment]
Testing it in zuul job with the above image here: https://review.rdoproject.org/r/c/testproject/+/46569/83/roles/external_compute_play/templates/edpm-play.yaml.j2#64

**Comment by raukadah** [comment]
> Testing it in zuul job with the above image here: https://review.rdoproject.org/r/c/testproject/+/46569/83/roles/external_compute_play/templates/edpm-play.yaml.j2#64

The migrated code works fine with the above image.
Logs: 
1. https://review.rdoproject.org/zuul/build/181abb1f2fd244c99865c04a144b2cf6/log/job-output.txt#1246
2.  Containers on EDPM node: https://logserver.rdoproject.org/69/46569/88/check/ansibleee-operator-github-rdo-integration-centos-8-crc-singlenode-centos-9-external-compute/181abb1/logs/secondary/podman_images.txt

**Review by raukadah — APPROVED** [review]
LGTM o/

**Review by kajinamit — APPROVED** [review]
lgtm

**Comment by kajinamit** [comment]
I know it's too later, but I'm wondering whether we should rename the role to edpm_chrony to make it consistent with the other services.

**Pull request merged**
