### PR TITLE
Updated ddp package option role

### PR DESCRIPTION
**Pull request by Jaganathancse**
This change is to update the ddp package option role and also updating molecule tests.

### CODE REVIEW

**Comment by Jaganathancse** [comment]
recheck

**Comment by Jaganathancse** [comment]
recheck

**Comment by Jaganathancse** [comment]
recheck

**Review by jpodivin — APPROVED** [review]

**Comment by Jaganathancse** [comment]
recheck

**Comment by Jaganathancse** [comment]
recheck

**Pull request merged**
