### PR TITLE
Reapply "Update telemetry role to deploy Kepler"

### PR DESCRIPTION
**Pull request by gibizer**
This reverts commit 1373c54ea0aa35eb93a52420fd093a3cc8a01271.

### CODE REVIEW

**Comment by yadneshk** [comment]
When it comes to merging kepler back please look at https://github.com/openstack-k8s-operators/edpm-ansible/pull/781 It creates a new dataplane service for Kepler and Ceilometer ipmi agent service. This makes deploying power monitoring services optional.

**Comment by gibizer** [comment]
> When it comes to merging kepler back please look at #781 It creates a new dataplane service for Kepler and Ceilometer ipmi agent service. This makes deploying power monitoring services optional.

This is not an attempt to re-enable kepler. I will let cloud ups manage that. It is just an attempt to help kepler devs producing an env where they can troubleshoot the slowness.

**Comment by gibizer** [comment]
data has been collected.

**Pull request closed without merging**
