### PR TITLE
Refactoring telemetry playbooks to be compliant with spec.

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Review by jlarriba — APPROVED** [review]

**Review by slagle — APPROVED** [review]

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
> These also need to be renamed to *.yaml to match all the other playbooks.

Done.

**Pull request merged**
