### PR TITLE
Add tasks to spawn ceilometer-ipmi agent container

### PR DESCRIPTION
**Pull request by yadneshk**

### CODE REVIEW

**Review by rebtoor — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

**Comment by yadneshk** [comment]
recheck

**Review by rebtoor — CHANGES_REQUESTED** [review]

**Comment by Sandeepyadav93** [comment]
recheck

**Comment by yadneshk** [comment]
@rebtoor thank you for reviewing this. I've made the changes you suggested, please take another look.

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
