### PR TITLE
Removed playbooks since they aren't used anymore

### PR DESCRIPTION
**Pull request by rebtoor**
edpm-ansible roles are now consumed by dataplane-operator, which define its set of playbooks inside the code, so the playbooks defined here aren't updated or maintained anymore.

The playbooks were still used only by `edpm-play` deploy in install_yamls repo, but there's a proposal to drop it: https://github.com/openstack-k8s-operators/install_yamls/pull/170

N.B. I'll put the PR on hold until epdm-play PR will be merged.

Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/170

### CODE REVIEW

**Review by fultonj — APPROVED** [review]
/lgtm 
+2
Thanks @rebtoor

**Review by raukadah — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Pull request merged**
