### PR TITLE
Add epdm_baremetal job

### PR DESCRIPTION
**Pull request by rabi**
Also fixes privilege escalation for package installation.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/292

### CODE REVIEW

**Review by bshephar — APPROVED** [review]

**Comment by raukadah** [comment]
@rabi Thank you for adding the job. The baremetal job is hitting [this issue](https://logserver.rdoproject.org/90/190/4f949e9f667e429256e09c0266dedf9dea6ea41f/github-check/edpm-ansible-crc-podified-edpm-baremetal/fc57232/ci-framework-data/logs/ci_make_000_run_edpm_compute_baremetal.log)
```
error: timed out waiting for the condition on nodenetworkconfigurationpolicies/enp6s0-crc-8tnb7-master-0
make[1]: *** [Makefile:1440: nncp] Error 1
gmake: *** [Makefile:98: edpm_compute_baremetal] Error 2
```

**Comment by rabi** [comment]
> @rabi Thank you for adding the job. The baremetal job is hitting [this issue](https://logserver.rdoproject.org/90/190/4f949e9f667e429256e09c0266dedf9dea6ea41f/github-check/edpm-ansible-crc-podified-edpm-baremetal/fc57232/ci-framework-data/logs/ci_make_000_run_edpm_compute_baremetal.log)
> 
> ```
> error: timed out waiting for the condition on nodenetworkconfigurationpolicies/enp6s0-crc-8tnb7-master-0
> make[1]: *** [Makefile:1440: nncp] Error 1
> gmake: *** [Makefile:98: edpm_compute_baremetal] Error 2
> ```

Yeah it would be fixed in install_yamls with https://github.com/openstack-k8s-operators/install_yamls/pull/320

**Comment by raukadah** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Review by raukadah — APPROVED** [review]
Let's force merge it, it will make baremetal job green.

**Pull request merged**
