### PR TITLE
adapt the telemetry playbooks to the new name and structure

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Review by jpodivin — APPROVED** [review]

**Comment by jlarriba** [comment]
This is linked to the new functionality of dataplane-operator: https://github.com/openstack-k8s-operators/dataplane-operator/pull/392

**Comment by jlarriba** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Pull request merged**
