### PR TITLE
Dropped custom strategy plugins, reverted to ansible-runner official image

### PR DESCRIPTION
**Pull request by rebtoor**
- Reverted to `quay.io/ansible/ansible-runner:latest` as base image (ansible 2.12)
- Dropped custom strategy plugins because probably they won't be supported
- Replaced `strategy: edpm_` in playbook with their official counterparts (e.g. `edpm_free` -> `free`)
- Added jmespath to requirements.txt since it's required by `ansible.builtin.template` module in task named "Update the default network configuration" for edpm-podman role.

I created an image with the updated base-image and code and used to successfully deploy a new node. The image is here: `quay.io/ralfieri/openstack-ansibleee-runner:original-runner`

### CODE REVIEW

**Review by slagle — APPROVED** [review]

**Comment by slagle** [comment]
This lgtm.

**Comment by bshephar** [comment]
lgtm

**Review by bshephar — APPROVED** [review]
All looks fine to me.

**Comment by rebtoor** [comment]
As for recent thread on Slack, we decided to restore `creator-ee` as base image, pinning its version to `v0.13.0` which contains ansible 2.14.1.

**Pull request merged**
