### PR TITLE
ovn_bgp_agent TLS

### PR DESCRIPTION
**Pull request by olliewalsh**
Configure OVN DB client certs when enabled

Related: [OSPRH-6543](https://issues.redhat.com//browse/OSPRH-6543)

### CODE REVIEW

**Comment by eduolivares** [comment]
recheck

**Comment by eduolivares** [comment]
recheck

Issue with podified-multinode-edpm-deployment-crc already resolved

**Comment by olliewalsh** [comment]
@karelyatin any way of testing this?

**Comment by karelyatin** [comment]
> @karelyatin any way of testing this?

@olliewalsh not sure if there is upstream ci job for it, I think @eduolivares working on some jobs internally, @eduolivares can you test this?

**Comment by eduolivares** [comment]
> > @karelyatin any way of testing this?
> 
> @olliewalsh not sure if there is upstream ci job for it, I think @eduolivares working on some jobs internally, @eduolivares can you test this?

Yes, I'm working on a BGP d/s job and hit an issue that hopefully will be fixed by this PR:
https://paste.opendev.org/show/bZX3kPdTwye0hMppaXYb/

We can test it on my setup, but I'd need some help to apply the fix.

**Comment by olliewalsh** [comment]
> > > @karelyatin any way of testing this?
> > 
> > @olliewalsh not sure if there is upstream ci job for it, I think @eduolivares working on some jobs internally, @eduolivares can you test this?
> 
> Yes, I'm working on a BGP d/s job and hit an issue that hopefully will be fixed by this PR:
> https://paste.opendev.org/show/bZX3kPdTwye0hMppaXYb/
> 
> We can test it on my setup, but I'd need some help to apply the fix.

Can do this https://openstack-k8s-operators.github.io/edpm-ansible/testing_with_ansibleee.html

**Review by eduolivares — APPROVED** [review]

**Pull request merged**
