### PR TITLE
[DNM] update containers check

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1580

### CODE REVIEW

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by rebtoor** [comment]
@raukadah can we close this PR?

**Comment by raukadah** [comment]
@rebtoor yes, thank you for the ping!

**Pull request closed without merging**
