### PR TITLE
Raising the bar on code compliance

### PR DESCRIPTION
**Pull request by jpodivin**
Most of the previously ignored style violations have been resolved. This includes unused imports and variables, as well as less intrusive style deficiencies.

Since we are starting essentially from scratch here I believe we should avoid perpetuating some of the issues that plagued our codebase before. Appropriate baseline is essential for this, as it prevents reintroduction of previously resolved problems. 

Any further code ported from tripleo-ansible will possibly require some changes to comply. But since it isn't going to be done in one go it should be manageable, while also offering an opportunity to look over some other cases inviting possible refactor. 

Signed-off-by: Jiri Podivin <jpodivin@redhat.com>

### CODE REVIEW

**Comment by jpodivin** [comment]
helpers.py were changed in the previous commit, I'll rebase and push again. At least this proves that the CI works.

**Comment by rebtoor** [comment]
100% agree on this @jpodivin !

**Comment by jpodivin** [comment]
It appears that the pr-check needs to be expanded to other states of PR. It didn't trigger when I force pushed a new patch.

**Comment by jpodivin** [comment]
This should make sure that action is triggered on PR when the hash changes. 
#16

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
