### PR TITLE
Add Zuul based molecule jobs

### PR DESCRIPTION
**Pull request by raukadah**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/177

Signed-off-by: Chandan Kumar <raukadah@gmail.com>

### CODE REVIEW

**Review by jpodivin — APPROVED** [review]
Great job on this thing.

**Comment by jpodivin** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
