### PR TITLE
 Add new ssh_known_hosts.yml playbook 

### PR DESCRIPTION
**Pull request by slagle**
The playbook will be run by a dedicated dataplane-operator service that
will be executed across all nodes.

Signed-off-by: James Slagle <jslagle@redhat.com>

### CODE REVIEW

**Review by gibizer — COMMENTED** [review]
you probably forgot to add the new playbook file to the commit

**Comment by slagle** [comment]
> you probably forgot to add the new playbook file to the commit

Indeed, it's added now.

**Comment by slagle** [comment]
This needs to be backwards compatible as the rdo job is failing with:

`
TASK [osp.edpm.edpm_container_manage : Create containers managed by Podman for /var/lib/openstack/config/containers] ***
[1;30mtask path: /usr/share/ansible/collections/ansible_collections/osp/edpm/roles/edpm_container_manage/tasks/create.yml:17[0m
[1;35m[WARNING]: ERROR: Container nova_compute exited with code 125 when runed[0m
[1;35mstderr: time="2024-02-27T19:25:50Z" level=info msg="podman filtering at log[0m
[1;35mlevel info" time="2024-02-27T19:25:50Z" level=info msg="Using sqlite as[0m
[1;35mdatabase backend" time="2024-02-27T19:25:50Z" level=info msg="Not using native[0m
[1;35mdiff for overlay, this may cause degraded performance for building images:[0m
[1;35mkernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled" time="2024-02-27T19:25:50Z"[0m
[1;35mlevel=info msg="Setting parallel job count to 25" time="2024-02-27T19:25:50Z"[0m
[1;35mlevel=info msg="Sysctl net.ipv4.ping_group_range=0 0 ignored in[0m
[1;35mcontainers.conf, since Network Namespace set to host" Error: statfs[0m
[1;35m/etc/ssh/ssh_known_hosts: no such file or directory[0m
[0;31mfatal: [compute-0]: FAILED! => {"changed": false, "msg": "Failed containers: nova_compute"}[0m
`

from https://logserver.rdoproject.org/74/574/7fd275ba6ccb081eb6a69b56e032a5d691654622/github-check/podified-multinode-edpm-deployment-crc/3ec11f9/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/nova-custom-openstack-edpm-2j5fj/logs/openstackansibleee.log

For now, I'll update this PR to just add the new playbook. A separate PR will drop the role from the configure_os playbooks once the dataplane PR https://github.com/openstack-k8s-operators/dataplane-operator/pull/712 merges.

**Comment by slagle** [comment]
I'm not going to recheck this one to get the rdo job to pass. this is just adding a new unused playbook.

**Review by jpodivin — APPROVED** [review]
lgtm, the dataplane-operator counterpart was merged

**Review by gibizer — APPROVED** [review]

**Pull request merged**
