### PR TITLE
Add firewall rule to include Kepler port

### PR DESCRIPTION
**Pull request by yadneshk**
Without this rule prometheus cannot scrape kepler metrics.

### CODE REVIEW

**Comment by yadneshk** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Comment by yadneshk** [comment]
recheck

**Comment by yadneshk** [comment]
```
  <instance> RUN [b'/usr/bin/podman', b'exec', b'instance', b'/bin/sh', b'-c', b'rm -f -r /root/.ansible/tmp/ansible-tmp-1731476703.4691613-29132-922438156212/ > /dev/null 2>&1 && sleep 0']
  [WARNING]: ERROR: Can't create container multipathd stderr:
  time="2024-11-13T05:45:09Z" level=info msg="podman filtering at log level info"
  time="2024-11-13T05:45:09Z" level=info msg="Using sqlite as database backend"
  time="2024-11-13T05:45:09Z" level=info msg="Setting parallel job count to 13"
  time="2024-11-13T05:45:09Z" level=info msg="Sysctl net.ipv4.ping_group_range=0
  0 ignored in containers.conf, since Network Namespace set to host" Error:
  statfs /etc/localtime: no such file or directory time="2024-11-13T05:45:09Z"
  level=info msg="Received shutdown.Stop(), terminating!" PID=1199
  fatal: [instance]: FAILED! => {
      "changed": false,
      "invocation": {
          "module_args": {
              "concurrency": 1,
              "config_dir": "/var/lib/edpm-config/container-startup-config/multipathd",
              "config_id": "multipathd",
              "config_overrides": {},
              "config_patterns": "*.json",
              "debug": false,
              "log_base_path": "/var/log/containers/stdouts"
          }
      },
      "msg": "Failed containers: multipathd"
  }
```

**Comment by yadneshk** [comment]
recheck

**Comment by danpawlik** [comment]
recheck

**Comment by yadneshk** [comment]
recheck

**Review by elfiesmelfie — CHANGES_REQUESTED** [review]

**Pull request merged**
