### PR TITLE
Explaining lack of tests for edpm_nova_libvirt role

### PR DESCRIPTION
**Pull request by jpodivin**
Exceedingly minor change, but it should probably get in for future reference.

### CODE REVIEW

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Review by SeanMooney — APPROVED** [review]

**Comment by SeanMooney** [comment]
depending on how things play out that role will probably get deleted sooner rather then later but it does not hurt to document this for now while it exits

**Comment by jpodivin** [comment]
recheck

**Pull request merged**
