### PR TITLE
Removing edpm_nova_compute and edpm_nova_libvirt roles

### PR DESCRIPTION
**Pull request by jpodivin**
Since the roles are no longer necessary, as their tasks are handled directly by nova operator, we can safely remove them.

### CODE REVIEW

**Review by fultonj — COMMENTED** [review]
+2

**Comment by booxter** [comment]
/lgtm

git actions will need to be cleaned up

**Comment by jpodivin** [comment]
> /lgtm
> 
> git actions will need to be cleaned up

I totally forgot about that :)

**Comment by SeanMooney** [comment]
it would be preferable to wait for https://github.com/openstack-k8s-operators/edpm-ansible/pull/334 to merge first to avoid conflicts but in general yes
i abandoned https://github.com/openstack-k8s-operators/edpm-ansible/pull/94 with the intent to repopose a new version this week anyway so I'm fine with using this pr to do that.

**Comment by jpodivin** [comment]
recheck

**Review by slagle — COMMENTED** [review]
This probably ought to wait on https://github.com/openstack-k8s-operators/edpm-ansible/pull/160 and https://github.com/openstack-k8s-operators/edpm-ansible/pull/334. After those, it lgtm.

**Comment by jpodivin** [comment]
> This probably ought to wait on #160 and #334. After those, it lgtm.

#160 Seems to be on hold for now. I would say that faster resolution may be to keep epm_nova_compute unmodified and merge changes after this PR.

**Comment by jpodivin** [comment]
recheck

**Comment by slagle** [comment]
> > This probably ought to wait on #160 and #334. After those, it lgtm.
> 
> #160 Seems to be on hold for now. I would say that faster resolution may be to keep epm_nova_compute unmodified and merge changes after this PR.

These are both merged now, but the resulting conflicts need to be fixed.

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
