### PR TITLE
Added EDPM based Zuul job

### PR DESCRIPTION
**Pull request by raukadah**

### CODE REVIEW

**Review by rebtoor — APPROVED** [review]

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Comment by raukadah** [comment]
https://review.rdoproject.org/r/c/config/+/48698 is merged now,

**Comment by raukadah** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Pull request merged**
