### PR TITLE
Don't gather all facts in molecule tests

### PR DESCRIPTION
**Pull request by rabi**
This will help us catch error with non available facts in molecule jobs.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2383

Jira: [OSPRH-10279](https://issues.redhat.com/browse/OSPRH-10279)

### CODE REVIEW

**Comment by rabi** [comment]
recheck  ceph job timeout when uploading logs

**Review by slagle — COMMENTED** [review]
recheck

**Review by slagle — APPROVED** [review]
approving, as it LGTM if it passes CI

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck adoption test failure, does not look related

**Comment by fao89** [comment]
recheck

**Comment by rabi** [comment]
@karelyatin Does  this[1] adoption job failure look like something to be fixed with https://github.com/openstack-k8s-operators/edpm-ansible/pull/766 ?

[1] https://logserver.rdoproject.org/67/767/8c99c5257d338ec67e7b5371931a22c92c241d65/github-check/adoption-standalone-to-crc-ceph-provider/8d9b822/controller/data-plane-adoption-tests-repo/data-plane-adoption/tests/logs/test_with_ceph_out_2024-09-27T23:31:29EDT.log

**Comment by karelyatin** [comment]
> @karelyatin Does this[1] adoption job failure look like something to be fixed with #766 ?
> 
> [1] https://logserver.rdoproject.org/67/767/8c99c5257d338ec67e7b5371931a22c92c241d65/github-check/adoption-standalone-to-crc-ceph-provider/8d9b822/controller/data-plane-adoption-tests-repo/data-plane-adoption/tests/logs/test_with_ceph_out_2024-09-27T23:31:29EDT.log

@rabi that's unrelated, but ^ is known issue being tracked in https://issues.redhat.com/browse/OSPCIX-503

**Comment by rabi** [comment]
> > @karelyatin Does this[1] adoption job failure look like something to be fixed with #766 ?
> > [1] https://logserver.rdoproject.org/67/767/8c99c5257d338ec67e7b5371931a22c92c241d65/github-check/adoption-standalone-to-crc-ceph-provider/8d9b822/controller/data-plane-adoption-tests-repo/data-plane-adoption/tests/logs/test_with_ceph_out_2024-09-27T23:31:29EDT.log
> 
> @rabi that's unrelated, but ^ is known issue being tracked in https://issues.redhat.com/browse/OSPCIX-503

Ah, Thanks @karelyatin , looks like https://github.com/openstack-k8s-operators/data-plane-adoption/pull/632 has merged a few hours ago, let's see if the job passes this time.

**Pull request merged**
