### PR TITLE
Enable download-cache for `edpm_tuned` role

### PR DESCRIPTION
**Pull request by rebtoor**
* removed `vars.yml` and `RedHat.yml` files since EL is the only supported distro.
* enabled retry mechanism for packages download/installation.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Pull request merged**
