### PR TITLE
Adding argument verification and documentation for edpm_timezone

### PR DESCRIPTION
**Pull request by jpodivin**
Tests for the role were augmented with proper verification stage and example of usage.

### CODE REVIEW

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Review by rebtoor — COMMENTED** [review]
+2

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Pull request merged**
