### PR TITLE
Network config args

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Review by slagle — APPROVED** [review]

**Comment by jpodivin** [comment]
recheck

`FAILED - RETRYING: [localhost]: Wait for OpenStack Provision Server pod to be created (1 retries left).`

**Comment by jpodivin** [comment]
recheck
`Wait for OpenStack Provision Server pod to be created (1 retries left).`

**Comment by jpodivin** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

ipam retry limit.

**Pull request merged**
