### PR TITLE
Adding configure_frr playbook

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Comment by jpodivin** [comment]
recheck

**Review by rebtoor — CHANGES_REQUESTED** [review]
We have used `ansible.builtin.import_roles` under `tasks` in all the other playbooks, but here we're using the `roles` directive. We should adapt this playbook to the style of the others IMHO.

**Comment by slagle** [comment]
> We have used `ansible.builtin.import_role` under `tasks` in all the other playbooks, but here we're using the `roles` directive. We should adapt this playbook to the style of the others IMHO.

:+1:

**Comment by slagle** [comment]
agreed. why change from what are already using in dataplane-operator?

**Review by slagle — APPROVED** [review]

**Pull request merged**
