### PR TITLE
Make `edpm_telemetry` role compliant with ansible-lint `production` profile

### PR DESCRIPTION
**Pull request by rebtoor**
- Fixed spacing issue
- Declared dicts in loop using long form to avoid line > 160 characters

### CODE REVIEW

**Comment by rebtoor** [comment]
recheck

retry_limit

**Comment by rebtoor** [comment]
recheck

**Comment by lewisdenny** [comment]
recheck
Due to a CI Blocker

**Comment by rebtoor** [comment]
recheck

**Review by jpodivin — APPROVED** [review]

**Pull request merged**
