### PR TITLE
Documenting main endpoint of the edpm_tuned role

### PR DESCRIPTION
**Pull request by jpodivin**
Also adjusting the molecule test to better represent the role usage.

This change will not only improve documentation of the project, but also introduce additional check on types of role input.

### CODE REVIEW

**Review by rebtoor — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

**Comment by jpodivin** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Pull request merged**
