### PR TITLE
Doc-Update: replace hugepages1g to hugepages1G

### PR DESCRIPTION
**Pull request by auniyal61**
doc update for edpm-extra-specs roles

### CODE REVIEW

**Comment by auniyal61** [comment]
retest
  * could not initialize namespace: timed out waiting for image pull secrets 
INFO[2024-10-17T10:46:45Z] Reporting job state 'failed' with reason 'initializing_namespace'

**Review by gibizer — APPROVED** [review]
Thanks Amit!

**Comment by gibizer** [comment]
recheck the baremetal job failed to install opensthift-marketplace

```
  stderr: 'error: You must be logged in to the server (Unauthorized)'
```

**Pull request merged**
