### PR TITLE
Adding install_os playbook

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Review by rebtoor — CHANGES_REQUESTED** [review]
`ansible.builtin.import_role`

**Review by rebtoor — APPROVED** [review]
as discussed in chat, let's import the playbook as is then, after verifying that everything is working, we will improve it.

**Comment by rebtoor** [comment]
@jpodivin be aware of this: https://github.com/openstack-k8s-operators/dataplane-operator/pull/335

cc @slagle

**Comment by slagle** [comment]
> @jpodivin be aware of this: [openstack-k8s-operators/dataplane-operator#335](https://github.com/openstack-k8s-operators/dataplane-operator/pull/335)
> 
> cc @slagle

Indeed, this will need to be updated to account for that change.

**Review by slagle — APPROVED** [review]

**Comment by ASBishop** [comment]
Is the intention that the dataplane service will be updated to invoke this new playbook instead of executing the list of tasks as it currently does?

The reason I ask is that I need to update the install/configure/run os tasks (for multipathd) and I need to know where to make the change.

**Pull request merged**
