### PR TITLE
Fix epdm -> edpm typos

### PR DESCRIPTION
**Pull request by slagle**
Signed-off-by: James Slagle <jslagle@redhat.com>

### CODE REVIEW

**Review by fao89 — APPROVED** [review]
so subtle

**Comment by rebtoor** [comment]
ahahahaah, totally my fault on this one! Thanks @slagle

**Comment by rebtoor** [comment]
Uhm, CI job is failed with error:

```
[0;31mfailed: [38.102.83.117] (item={'key': 'nova_virtqemud', 'value': {'start_order': 4, 'image': 'quay.io/tripleomastercentos9/openstack-nova-libvirt:current-tripleo', 'ulimit': ['nofile=131072', 'nproc=126960'], 'cgroupns': 'host', 'net': 'host', 'pid': 'host', 'pids_limit': 65536, 'privileged': True, 'security_opt': ['label=level:s0', 'label=type:spc_t', 'label=filetype:container_share_t'], 'restart': 'always', 'depends_on': ['edpm_nova_virtlogd.service'], 'volumes': ['/etc/hosts:/etc/hosts:ro', '/etc/localtime:/etc/localtime:ro', '/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro', '/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro', '/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro', '/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro', '/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro', '/dev/log:/dev/log', '/lib/modules:/lib/modules:ro', '/dev:/dev', '/run:/run', '/sys/fs/cgroup:/sys/fs/cgroup', '/sys/fs/selinux:/sys/fs/selinux', '/etc/selinux/config:/etc/selinux/config:ro', '/etc/libvirt:/etc/libvirt:shared', '/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro', '/run/libvirt:/run/libvirt:shared', '/var/lib/nova:/var/lib/nova:shared', '/var/lib/libvirt:/var/lib/libvirt:shared', '/var/cache/libvirt:/var/cache/libvirt:shared', '/var/lib/vhost_sockets:/var/lib/vhost_sockets', '/var/log/containers/libvirt:/var/log/libvirt:shared,z', '/var/lib/config-data/ansible-generated/nova_libvirt:/var/lib/kolla/config_files/src:ro', '/var/lib/edpm-config/ceph:/var/lib/kolla/config_files/src-ceph:ro', '/var/lib/kolla/config_files/nova_virtqemud.json:/var/lib/kolla/config_files/config.json:ro'], 'environment': {'KOLLA_CONFIG_STRATEGY': 'COPY_ALWAYS'}}}) => {"ansible_loop_var": "item", "item": {"key": "nova_virtqemud", "value": {"cgroupns": "host", "depends_on": ["edpm_nova_virtlogd.service"], "environment": {"KOLLA_CONFIG_STRATEGY": "COPY_ALWAYS"}, "image": "quay.io/tripleomastercentos9/openstack-nova-libvirt:current-tripleo", "net": "host", "pid": "host", "pids_limit": 65536, "privileged": true, "restart": "always", "security_opt": ["label=level:s0", "label=type:spc_t", "label=filetype:container_share_t"], "start_order": 4, "ulimit": ["nofile=131072", "nproc=126960"], "volumes": ["/etc/hosts:/etc/hosts:ro", "/etc/localtime:/etc/localtime:ro", "/etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro", "/etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro", "/etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro", "/etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro", "/etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro", "/dev/log:/dev/log", "/lib/modules:/lib/modules:ro", "/dev:/dev", "/run:/run", "/sys/fs/cgroup:/sys/fs/cgroup", "/sys/fs/selinux:/sys/fs/selinux", "/etc/selinux/config:/etc/selinux/config:ro", "/etc/libvirt:/etc/libvirt:shared", "/etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro", "/run/libvirt:/run/libvirt:shared", "/var/lib/nova:/var/lib/nova:shared", "/var/lib/libvirt:/var/lib/libvirt:shared", "/var/cache/libvirt:/var/cache/libvirt:shared", "/var/lib/vhost_sockets:/var/lib/vhost_sockets", "/var/log/containers/libvirt:/var/log/libvirt:shared,z", "/var/lib/config-data/ansible-generated/nova_libvirt:/var/lib/kolla/config_files/src:ro", "/var/lib/edpm-config/ceph:/var/lib/kolla/config_files/src-ceph:ro", "/var/lib/kolla/config_files/nova_virtqemud.json:/var/lib/kolla/config_files/config.json:ro"]}}, "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /root/.ansible/tmp `\"&& mkdir \"` echo /root/.ansible/tmp/ansible-tmp-1678308718.457832-3726-30089142330438 `\" && echo ansible-tmp-1678308718.457832-3726-30089142330438=\"` echo /root/.ansible/tmp/ansible-tmp-1678308718.457832-3726-30089142330438 `\" ), exited with result 1", "unreachable": true}[0m
```

**Review by rebtoor — APPROVED** [review]

**Comment by rebtoor** [comment]
recheck

**Pull request merged**
